kind: pipeline
type: docker
name: default

trigger:
  event:
    - push
  branch:
    - master

steps:
  - name: docker
    image: plugins/docker
    settings:
      registry: r.s8k.top
      username: docker
      password:
        from_secret: DOCKER_REGISTRY_PASSWD
      repo: r.s8k.top/se-docs
    when:
      branch:
        - master
      event:
        - push
  - name: deploy
    image: plugins/webhook
    settings:
      method: POST
      urls: https://deploy.s8k.top/api/services/se-docs/deploy
      headers:
        from_secret: COMPOSE_DEPLOYER_SECRET_HEADER
    when:
      branch:
        - master
    depends_on:
      - docker

---
kind: pipeline
type: docker
name: default

triger:
  event:
    - pr
  branch:
    - master

steps:
  - name: check
    image: plugins/docker
    repo: docs-test
    dry_run: true
