kind: pipeline
type: docker
name: publish

trigger:
  event:
    - push
  branch:
    - master

steps:
  - name: docker
    image: plugins/docker
    settings:
      registry: r.s8k.top
      username: docker
      password:
        from_secret: DOCKER_REGISTRY_PASSWD
      repo: r.s8k.top/se-docs
      purge: false
  - name: deploy
    image: plugins/webhook
    settings:
      method: POST
      urls: https://deploy.s8k.top/api/services/se-docs/deploy
      headers:
        from_secret: COMPOSE_DEPLOYER_SECRET_HEADER
    depends_on:
      - docker

---
kind: pipeline
type: docker
name: check

triger:
  event:
    - push
  branch:
    exclude:
      - master

steps:
  - name: check
    image: plugins/docker
    settings:
      registry: r.s8k.top
      username: docker
      password:
        from_secret: DOCKER_REGISTRY_PASSWD
      repo: docs-test
      purge: false
      dry_run: true

