kind: pipeline
type: docker
name: default

steps:
  - name: Build and publish docker image
    image: plugins/docker
    settings:
      registry: r.s8k.top
      username: docker
      password:
        from_secret: DOCKER_REGISTRY_PASSWD
      repo: r.s8k.top/se-docs
  - name: Deploy
    image: plugins/webhook
    settings:
      method: POST
      urls: https://deploy.s8k.top/api/services/se-docs/deploy
      headers:
        from_secret: COMPOSE_DEPLOYER_SECRET_HEADER
